### ISSUE TITLE
Basic gems out of date?

### ISSUE THREAD

**Issue by tilsammans** [davetron5000/angular-rails-book#32]
When I read the [Basic Gems](http://angular-rails.com/bootstrap.html#basic-gems) chapter, I notice it might be out of date?

```
Note that we're also pinning version 3.2.19 of the sass gem.
```

Looks like the receta master isn't pinning it.

Also, the `Gemfile` in master is very different from the small diff you're showing in the book. It might be better to point to the raw `Gemfile` in the repo? It will always be up to date.

I'd like to submit a PR for this, if you're cool with the changes.

**Comment by davetron5000** [comment]
Yeah, if you look at receta, there's a ton of branches and tags, which are used to generate some of those diffs.  But then, some got out of date, and it was really hard to update.

I think, in general, I want to keep the gems updated, and it's possible the issue with sass has been resolved.

If you want to do a PR, that would be awesome.  I *think* if you do a change to receta, try to keep the changes to `Gemfile` and `Gemfile.lock` in their own commit, so I can cherry-pick that onto the various branches used to generate the source.

**Comment by tilsammans** [comment]
My eyes start to bleed when I look at the default new `Gemfile` from a fresh Rails app. So much useless comments, so little structure... the actual Gemfile in your repo is much nicer. So the diff is going to be rather large.

I don't know what your preference would be. Putting a clean Gemfile in the book or trying to make sense of the diffs?

Anyway I will first verify that sass-rails 5.0.3 works with the app. Will report back. :)

**Comment by tilsammans** [comment]
sass-rails works! but i decided to abandon the site anyway and go with a plain Angular app and use a different back end. it's just easier for me. i will close this issue for now and possibly revisit in the future. thanks
