### ISSUE TITLE
Trouble Loading Bootstrap Icons

### ISSUE THREAD

**Issue by verdi327** [davetron5000/angular-rails-book#36]
Not sure what has changed since when you lasted updated but following the instructions for setting up bootstrap using bower doesn't appear to be playing nicely.  I can load the bootstrap stylesheets, but the fonts are causing trouble.

The issue occurs when trying to `@import "bootstrap-sass-official/assets/stylesheets/bootstrap-sprockets";`

![screen shot 2015-05-21 at 4 46 50 pm](https://cloud.githubusercontent.com/assets/1141380/7761299/052fd73e-ffd9-11e4-8919-baee4b08d9ba.png)

I've read about this potentially being an issue with sprocket-rails but changing the gem version didn't fix it for me. https://github.com/rails/sprockets-rails/issues/217

Here's my `config/application.rb`
````
config.assets.paths << Rails.root.join("lib","assets","bower_components")
config.assets.paths << Rails.root.join("lib","assets","bower_components","bootstrap-sass-official","assets","fonts")
config.assets.precompile << %r(.*.(?:eot|svg|ttf|woff)$)
````

Using Rails 4.2, Ruby 2.1.3

**Comment by davetron5000** [comment]
Do you know what version of bootstrap you have installed?

**Comment by davetron5000** [comment]
I just did a `bundle update` and `rake bower:update:prune` in davetron5000/receta and everything seems to be working.

My config seems to be the same as yours, too.  I can't push my changes ATM (Google Starbucks Wifi!!!!), but I'll ping back here when I can.

**Comment by verdi327** [comment]
I'm using Bootstrap Sass 3.3.4 which I believe tries to stay parallel with Bootstrap's official version

**Comment by verdi327** [comment]
So, I got this working.  I changed my `config/application.rb` file to look like:

````
root.join('lib', 'assets', 'bower_components').to_s.tap do |bower_path|
    config.sass.load_paths << bower_path
    config.assets.paths << bower_path
 end

config.assets.precompile << %r(bootstrap-sass-official/assets/fonts/bootstrap/[\w-]+\.(?:eot|svg|ttf|woff2?)$)
::Sass::Script::Value::Number.precision = [8, ::Sass::Script::Value::Number.precision].max
````

I then added these 2 lines into my `config/initalizers/assets.rb`

````
Rails.application.config.assets.precompile += %w( bootstrap/glyphicons-halflings-regular.eot )
Rails.application.config.assets.precompile += %w( bootstrap/glyphicons-halflings-regular.woff2 )
````

And inside my `application.css.scss` I added

````
 $icon-font-path: "bootstrap-sass-official/assets/fonts/bootstrap/";
````

**Comment by davetron5000** [comment]
Wow, that seems crazy.  Did my updated branch of receta work for you without any of that?  What I don't understand is why you had to explicitly add the fonts for precompilation in two places.  And what is up with this: `::Sass::Script::Value::Number.precision = [8, ::Sass::Script::Value::Number.precision].max`?
